#!/usr/bin/env python3
"""Generate the native hook's bundled dialogue lookup from the canonical catalogs."""
from __future__ import annotations

import argparse
import re
from pathlib import Path

LOCALES = ("en", "fr", "it", "de", "es", "pt", "ru", "ko", "zh-CN", "zh-TW", "ja", "tr", "nl", "ar", "th", "id")
ROOT_DIR = Path(__file__).resolve().parents[2]
CATALOG_DIR = ROOT_DIR / "client/StoryPort/Assets/Resources/StoryPort/Localization"
PLACEHOLDER = re.compile(r"%[0-9$]*[sdif]|\{[A-Za-z_][A-Za-z0-9_.-]*}")
MARKUP = re.compile(r"</?[A-Za-z][A-Za-z0-9]*(?:\s+[^<>]*?)?/?>")


def read_catalog(locale: str) -> dict[str, str]:
    path = CATALOG_DIR / f"dialogue_{locale}.txt"
    entries: dict[str, str] = {}
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not raw or raw.startswith("#"):
            continue
        if "\t" not in raw:
            raise ValueError(f"{path}:{number}: expected KEY<TAB>text")
        key, escaped = raw.split("\t", 1)
        if not key or key in entries:
            raise ValueError(f"{path}:{number}: empty or duplicate key {key!r}")
        value: list[str] = []
        index = 0
        while index < len(escaped):
            if escaped[index] == "\\" and index + 1 < len(escaped):
                index += 1
                value.append({"n": "\n", "t": "\t"}.get(escaped[index], escaped[index]))
            else:
                value.append(escaped[index])
            index += 1
        entries[key] = "".join(value)
    return entries


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r").replace("\t", "\\t") + '"'


def generate(output: Path) -> None:
    catalogs = {locale: read_catalog(locale) for locale in LOCALES}
    baseline = catalogs["en"]
    dialogue_keys = [key for key in baseline if key.startswith("ID_STORY_") and not key.startswith("ID_STORY_UI_")]
    if len(dialogue_keys) != 42:
        raise ValueError(f"expected 42 native dialogue keys, found {len(dialogue_keys)}")
    if len({baseline[key] for key in dialogue_keys}) != len(dialogue_keys):
        raise ValueError("English dialogue source lines must be unique for native lookup")
    for locale, catalog in catalogs.items():
        if list(catalog) != list(baseline):
            raise ValueError(f"{locale} catalog keys or ordering differ from English")
        for key in dialogue_keys:
            value = catalog[key]
            if not value.strip():
                raise ValueError(f"{locale} translation {key} is empty")
            if sorted(PLACEHOLDER.findall(value)) != sorted(PLACEHOLDER.findall(baseline[key])):
                raise ValueError(f"{locale} translation {key} changes placeholders")
            if sorted(MARKUP.findall(value)) != sorted(MARKUP.findall(baseline[key])):
                raise ValueError(f"{locale} translation {key} changes markup")

    lines = [
        "/* Generated by tools/nativehook/generate_dialogue_header.py; do not edit. */",
        "struct TftfDialogueTranslation { const char *source; const char *locale[17]; };",
        "static const char* tftf_dialogue_locale_text(const struct TftfDialogueTranslation *entry, int language) {",
        "    return entry && language >= 1 && language <= 16 ? entry->locale[language] : NULL;",
        "}",
        "static const struct TftfDialogueTranslation g_tftf_dialogue_translations[] = {",
    ]
    for key in dialogue_keys:
        values = ["NULL"]
        values.extend(c_string(catalogs[locale][key]) for locale in LOCALES)
        lines.append("    { " + c_string(baseline[key]) + ", { " + ", ".join(values) + " } },")
    lines.extend(["};", f"#define TFTF_DIALOGUE_TRANSLATION_COUNT {len(dialogue_keys)}", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    temp = output.with_suffix(output.suffix + ".tmp")
    generated = "\n".join(lines)
    if output.exists() and output.read_text(encoding="utf-8") == generated:
        return
    temp.write_text(generated, encoding="utf-8")
    temp.replace(output)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    generate(args.output)
