FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        libasound2 \
        libdbus-1-3 \
        libfontconfig1 \
        libfreetype6 \
        libgl1 \
        libglu1-mesa \
        libgtk-3-0 \
        libgdk-pixbuf2.0-0 \
        libicu66 \
        libnss3 \
        libpulse0 \
        libssl1.1 \
        libunwind8 \
        libxml2 \
        libx11-6 \
        libxcursor1 \
        libxext6 \
        libxinerama1 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        python3 \
        zlib1g \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
